### ISSUE TITLE
单独从bee-checkbox引入的时候，CheckboxGroup渲染、样式错误

### ISSUE THREAD

**Issue by tongchong** [tinper-bee/bee-checkbox#6]
引入方式：
import Checkbox from 'bee-checkbox';
import "./node_modules/build/bee-checkbox.css";
import Form from 'bee-form';
const { FormItem } = Form;
const CheckboxGroup = Checkbox.CheckboxGroup;
<CheckboxGroup
                                    {
                                    ...getFieldProps('moudleName', {
                                        initialValue: moudleName,
                                        onChange: self.onChangeCheckbox
                                    })
                                    }
                                >
                                    {moudleArr.map((item,index) => {
                                        return (
                                            <Checkbox key={index} value={item.id }>{item.moudleName}</Checkbox>
                                        )
                                    })}
                                </CheckboxGroup>

**Comment by lucian55** [comment]
import 'bee-checkbox/build/Checkbox.css'
